name: Publish

on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          registry-url: "https://registry.npmjs.org"
      - name: Check Release type and Publish
        run: |
          if ${{ github.event.release.prerelease }}; then
            echo "Publishing pre-release..."
            npm publish --verbose --access=public --tag next
          else
            echo "Publishing release..."
            npm publish --verbose --access=public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
